app_name: 'go-clean-backend'
env: dev
debug_port: '40000'

http:
  port: '8080'

log:
  level: 'debug'
  encoding: console
  encode_time: '2006-01-02T15:04:05.000Z0700'
  filename: './logs/service.log'
  max_size: 1024
  max_backups: 30
  max_age: 30
  compress: true
  encode_level: '[level]'
  use_stdout: true

mysql:
  host: 'nas.top'
  port: '3306'
  username: 'clean'
  password: '123456'
  dbname: 'go-clean-backend'
  config: 'charset=utf8&parseTime=true'
  max_idle_conns: 10
  max_open_conns: 100
  max_life_time: 3600

redis:
  addr: 'nas.top:6379'
  password: ''
  db: 0